Create stage4 view and view-model
PrimeDAO/prime-launch-dapp pull request #15
Opened 2021-05-07 03:43 UTC by Peartes

[X] Created the view for the stage4 component and make this view match the spec
[x] Implemented validation on the stage

2021-05-07 18:44 UTC, dkent600 requested changes

2021-05-07 18:44 UTC, dkent600 commented on src/newSeed/baseStage.scss
>  @import "styles/colors";
replace with

`@import "styles/styles.scss"`

2021-05-07 18:44 UTC, dkent600 commented on src/newSeed/stage4.html
> +              value.bind="seedConfig.seedDetails.startTime" placeholder="13:37 (UTC)"></numeric-input>
make it:  "00:00 (UTC)"

2021-05-07 21:49 UTC, dkent600 commented on src/newSeed/seedConfig.ts
> +  startDate: string,
(by "I don't think we should have separate fields" I am referring to this stageCOnfig object, not the UI)

2021-05-07 21:51 UTC, dkent600 commented on src/newSeed/seedConfig.ts
> +  seedTokens: BigNumber,
Created a card here: https://www.notion.so/curvelabs/All-BigNumber-fields-in-ISeedConfig-should-be-strings-804afa1787e74283bd431c8925631ffd

2021-05-08 02:19 UTC, Peartes commented on src/newSeed/seedConfig.ts
> +  seedTokens: BigNumber,
Okay

2021-05-08 19:47 UTC, dkent600 commented on src/newSeed/stage4.html
> +              value.bind="seedConfig.seedDetails.startTime" placeholder="13:37 (UTC)"></numeric-input>
Sorry, should be:  00:00 (GMT)

2021-05-08 20:58 UTC, dkent600 approved these changes

2021-05-08 20:59 UTC, merged