chore: reduce font size over stages numbers
PrimeDAO/prime-launch-dapp pull request #428
Opened 2021-11-03 12:45 UTC by sunguru98

The sidebar numbers' font size is now a bit smaller

## Screenshots

New LBP (Desktop)
<img width="1067" alt="Screenshot 2021-11-03 at 6 13 08 PM" src="https://user-images.githubusercontent.com/32637757/140062016-0b924869-5bcb-4c1f-8bd8-5cdb588638cc.png">

New LBP (Mobile)
<img width="375" alt="Screenshot 2021-11-03 at 6 13 39 PM" src="https://user-images.githubusercontent.com/32637757/140062079-5d6ee60b-8f22-47df-9058-b7e9b9242b3f.png">

New Seed (Desktop)
<img width="1038" alt="Screenshot 2021-11-03 at 6 15 00 PM" src="https://user-images.githubusercontent.com/32637757/140062280-a2be2add-13bf-4d7a-8a90-aedc512518a4.png">

New Seed (Mobile)
<img width="370" alt="Screenshot 2021-11-03 at 6 14 20 PM" src="https://user-images.githubusercontent.com/32637757/140062213-72caeaa1-fce8-4182-9695-130110b39614.png">

2021-11-03 15:15 UTC, dkent600 commented
@BartuCulha Can you please confirm whether you wanted the desktop numbers to change size too?  THanks

2021-11-03 15:20 UTC, BartuCulha commented
All looks good @dkent600 , no need to change Desktop Numbers

2021-11-03 15:34 UTC, sunguru98 commented
Gotcha, will change them @BartuCulha :)

2021-11-03 15:38 UTC, sunguru98 commented
Changes made as per above statement

# Mobile
![Screenshot 2021-11-03 at 9.07.19 PM.png](https://images.zenhubusercontent.com/5f8d6e841445bac8d3b34527/c8a9d33c-f161-4f1a-84f5-b07ca633464b)

# Desktop
![Screenshot 2021-11-03 at 9.08.06 PM.png](https://images.zenhubusercontent.com/5f8d6e841445bac8d3b34527/d94c4749-c54b-4567-8364-c623359b2ecd)

2021-11-03 16:09 UTC, dkent600 requested changes
Shouldn't affect the desktop

2021-11-03 16:18 UTC, sunguru98 commented
Font sizes updated as per asked above 

1. Desktop
<img width="229" alt="Screenshot 2021-11-03 at 9 45 31 PM" src="https://user-images.githubusercontent.com/32637757/140099640-c6a4128f-87a2-40ab-b52e-9b322e857dfc.png">

2. Mobile
<img width="244" alt="Screenshot 2021-11-03 at 9 48 18 PM" src="https://user-images.githubusercontent.com/32637757/140100107-a0b81420-0b61-40bc-837d-8bb043cfaed7.png">

2021-11-04 09:15 UTC, dkent600 approved these changes

2021-11-04 09:16 UTC, merged