feat: display link to the launch in the launch admin page
PrimeDAO/prime-launch-dapp pull request #447
Opened 2021-11-08 07:39 UTC by wantedsystem

2021-11-08 13:15 UTC, dkent600 requested changes
Please provide a screenshot

2021-11-08 13:15 UTC, dkent600 commented on src/admin/lbps/dashboard/dashboard.html
> +      <a href.to-view="lbp/${selectedLbp.address}">Go to LBP Dashboard</a>
Do these links show if there is no selected token?  They should not.

2021-11-08 16:46 UTC, dkent600 requested changes
Can you please supply a screenshot?  THanks

2021-11-08 17:39 UTC, wantedsystem commented
Results =>

<img width="1093" alt="Capture d’écran 2021-11-08 à 18 38 21" src="https://user-images.githubusercontent.com/11537417/140791106-898b199f-e75a-46b7-abf9-ec5a0d0ff37e.png">

2021-11-09 10:08 UTC, dkent600 approved these changes

2021-11-09 10:14 UTC, dkent600 approved these changes

2021-11-09 10:14 UTC, merged