Cliff and vest should be able to be 0
PrimeDAO/prime-launch-dapp pull request #568
Opened 2021-11-24 19:34 UTC by wantedsystem

2021-11-24 21:26 UTC, dkent600 requested changes

2021-11-24 21:26 UTC, dkent600 commented on src/newLaunch/seed/stages/stage4.ts
>        message = "Please enter a number greater than zero for  \"Project tokens vested for\" ";
message should be "greater than or equal"

2021-11-24 21:26 UTC, dkent600 commented on src/newLaunch/seed/stages/stage4.ts
> +    } else if (this.launchConfig.launchDetails.vestingPeriod===null || this.launchConfig.launchDetails.vestingPeriod===undefined) {
Is there any chance can be undefined?  Maybe easier to check if is a number?  Like `Number.isInteger` and >= 0?  (note that you are allowed < 0)

2021-11-25 15:37 UTC, dkent600 approved these changes

2021-11-25 15:38 UTC, dkent600 approved these changes
@wantedsystem  Can you please fix the merge conflicts?

2021-11-29 14:56 UTC, wantedsystem commented
@dkent600 merge conflict fixed

2021-11-29 19:42 UTC, dkent600 approved these changes

2021-11-29 19:43 UTC, merged