Etherscan link column
PrimeDAO/prime-launch-dapp pull request #57
Opened 2021-06-08 17:10 UTC by Peartes

This commit adds a new column to the launches table showing the address of the newly deployed seed and serving as a link to etherscan.io. 

This commit addresses this issue [here](https://www.notion.so/curvelabs/339a249185e14ddcbd731e5ba07c46c7?v=f7cba822bb9043a5a87ab80b5e2b40ef&p=6d812f0f135d45c1834328168d16b31f)

2021-06-11 14:02 UTC, dkent600 requested changes
can you please bring this up to the latest in master.  It currently won't build.

2021-06-12 11:28 UTC, Peartes commented
> can you please bring this up to the latest in master.  It currently won't build.

Sure

2021-06-12 15:25 UTC, dkent600 commented on src/launches/launches.html
> +              <div class="cell cap ${(($index >= 4) && !seeingMore) ? 'hideMore' : ''} ${seed.hasSeedTokens ? 'hot' : '' }">$ <formatted-number average mantissa="2" value.to-view="seed.cap | ethwei">
Has changed again.  Should be canGoToDashboard.

2021-06-14 14:47 UTC, dkent600 approved these changes

2021-06-14 14:47 UTC, merged