display image by input of a valid url
PrimeDAO/prime-launch-dapp pull request #80
Opened 2021-06-25 11:07 UTC by giladt

Added an image after the `.infoInput` element.
Added validation for broken links.
Added styling for max width/height of 400px.

Tested on both web/mobile views.

2021-06-25 12:07 UTC, dkent600 requested changes

2021-06-25 12:07 UTC, dkent600 commented on src/newSeed/stage2.ts
> +      message = "No image found under the provided Project Logo URL";
make it:  "No image found at the provided Project Logo URL"

2021-06-25 12:07 UTC, dkent600 commented on src/newSeed/stage2.ts
> +  private isLinkNotBroken(url: string): boolean {
I am getting this for a valid url.

![image](https://user-images.githubusercontent.com/1821666/123422271-3281e780-d57b-11eb-8269-6c5f99a38433.png)

2021-06-25 12:07 UTC, dkent600 commented on src/newSeed/stage2.ts
> +  private isLinkNotBroken(url: string): boolean {
I'm getting the same error for an invalid URL, but I should not be getting an error at all until the user moves on from the page.

![image](https://user-images.githubusercontent.com/1821666/123422440-7117a200-d57b-11eb-8adb-b2679f6f3292.png)

2021-06-26 20:38 UTC, giladt commented
I haven't changed much since the last commit. Tried different approaches, but the problem is that external URLs are blocked by **CORS** rules, and I can not do anything from the front end to avoid it.
I have tried adding headers to the _devServer_ in _webpack.config.js_ but I'm not sure if I did it correctly or not (didn't commit that as it didn't work) and anyway it should be defined in the production environment too, which may imply security issues...

It works correctly with local images - e.g. `/favicon-32x32.png`
or some cdn images (I guess its whitelisted?) - e.g. `https://gblobscdn.gitbook.com/spaces%2F-MH0VrbEUlD_Vg90Gx8g%2Favatar-1599902686246.png`.

2021-06-27 22:49 UTC, dkent600 approved these changes

2021-06-27 22:49 UTC, merged